Code Review (DB diagram)
efrapp/facebook pull request #1
Opened 2019-05-21 16:43 UTC by efrapp

2019-05-22 09:57 UTC, rvvergara approved these changes
Hi @efrapp and @userman95,

Congratulations on coming this far! This is your final Rails project (at least from the program's standpoint). So we'll be making sure you build a very nice app.

## Suggested Testing Framework
First I'd like to say to use RSpec for testing. In my experience, it's much easier to write specs/tests and the test data is less brittle as it uses `factories` instead of `fixtures`.

## ERD

I think you should fill up your `Post`, `Like` and `Comment` as they don't depict the `user_id`. We should not be able to create `posts`, `comments` or `likes` without them attached to a `user`.

For other matters that may arise from your data architecture we can tackle once you have created your models. Please be sure to test each of your models for validations and associations. And before even starting to create controllers or views let's first make sure all your models are stable. For this, the `rails console` is your best friend. You will need to try out all the features of your models there. 

Ok, I believe you are ready now to move on and build your models. So:

# :+1:

2019-05-22 09:57 UTC, rvvergara commented on Gemfile
> +gem 'hirb'
You might wanna put this gem into the `development, test` group. Also I suggest using `pry-rails` in addition to `hirb`. Makes your console display look so much better :)

2019-05-24 15:28 UTC, efrapp commented
Sending new code review for Models

2019-05-25 03:30 UTC, rvvergara requested changes
Hi @efrapp and @userman95,

Great leap forward in building your models! Though there are some work we need to do. Please see my comments in the respective model files and issue #4.

In regards to testing, please use RSpec as your testing framework. Minitest is good but RSpec is more robust, less brittle and more widely used. Read [this](https://medium.com/back-to-rails/setting-up-rspec-testing-for-rails-5-28be8431f845) for more information on how to set up RSPec for your project. Use `factory_bot_rails` instead of the `factory_girl` gem mentioned in that article.

2019-05-25 03:30 UTC, rvvergara commented on db/schema.rb
> +  create_table "comments", force: :cascade do |t|
Why aren't we referencing `user` here in comments? It will be a problem in your implementation later on without such reference.

See #4

2019-05-25 03:30 UTC, rvvergara commented on db/schema.rb
> +  create_table "likes", force: :cascade do |t|
Like in `comments`, why are we not referencing `user` here? 

See #4

2019-05-25 03:30 UTC, rvvergara commented on app/models/user.rb
> +  has_many :requests,
Why did we use `:requests` as association name for 'Friendship`? Why not `:friends`? This is a little confusing

2019-05-25 03:30 UTC, rvvergara commented on app/models/user.rb
> +  has_many :invitations,
Same comment as for `:requests` above.

I recognize what you wanna do here. You want to distinguish a user that initiated the friendship vs the user that received the friend invitation. So I would stick to simple `sent_requests` and `received_requests` to make this more explicit.

2019-05-25 03:30 UTC, rvvergara commented on app/models/user.rb
> +  has_many :invitations_from, through: :invitations, source: :sender
How can we, for instance, know `efrain` 's list of friends (which means those that have accepted his friend requests or those whose friend requests efrain already accepted)?

We probably need a method that will let us list all of a user's set of friends.

2019-05-25 03:30 UTC, rvvergara commented on app/models/user.rb
> +  has_many :likes
Are we not also destroying a `user` 's `comments` and `likes` should the `user` 's account be destroyed?

2019-05-25 03:30 UTC, rvvergara commented on app/models/comment.rb
> +class Comment < ApplicationRecord
See issue #4

2019-05-25 03:30 UTC, rvvergara commented on app/models/like.rb
> +class Like < ApplicationRecord
See issue #4

2019-05-27 15:06 UTC, efrapp commented on app/models/user.rb
> +  has_many :requests,
Ok Ryan, I changed `:requests` to `:sent_requests`.

2019-05-27 15:07 UTC, efrapp commented on app/models/user.rb
> +  has_many :invitations,
Same here. I changed `invitations` to `received_requests`.

2019-05-27 17:01 UTC, efrapp commented on app/models/user.rb
> +  has_many :invitations_from, through: :invitations, source: :sender
If we want all the friends that accepted the `efrain`'s request we can do this:
```
efrain.sent_requests.where(accepted: true)
```
And if we want the friend requests `efrain` already accepted we can use:
```
efrain.received_requests.where(accepted: true)
```
I also made two test cases for that.

2019-05-27 17:30 UTC, efrapp commented on app/models/user.rb
> +  has_many :likes
Ok, we added the `dependent` option for both, `likes` and `comments`.

2019-05-28 13:05 UTC, efrapp commented on db/schema.rb
> +  create_table "comments", force: :cascade do |t|
User reference added to comments.

2019-05-28 13:05 UTC, efrapp commented on db/schema.rb
> +  create_table "likes", force: :cascade do |t|
User reference added to likes.

2019-05-28 13:06 UTC, efrapp commented on app/models/comment.rb
> +class Comment < ApplicationRecord
The `belongs_to` association is already placed in the model.

2019-05-28 13:07 UTC, efrapp commented on app/models/like.rb
> +class Like < ApplicationRecord
`belongs_to` added to Like model too.

2019-05-28 13:08 UTC, efrapp commented
Changes finished for second code review on models

2019-05-29 08:25 UTC, rvvergara requested changes
Hi @efrapp and @userman95,

Pls see my latest reviews. I would normally not want to get in your way on how you design your data architecture. But I think it would be better if you have a separate model for recording FriendRequests rather than stuffing it all up under `Friendship`. Here are my two cents worth:

1. As a data maintainer you will have an easier time handling massive records later on. Stuffing all friend requests as if they're already friendships will make it confusing later on. This is even if you have the `accepted` column. Do I say `mike` has `ryto` as a friend even if `ryto` has not accepted mike yet as a friend?

2. Related to my comment in `user.rb` and 1) above, it makes your db query more complicated.

But then again it is entirely up to you on how to implement this. I just wanted to share a better approach in my perspective. 

I also suggest you make full use of your models as the home to your advanced database querying. Controllers should just, for the most part, do simple `find` and/or `find_by` queries. This is in relation to the **fat-model thin-controller** principle. I haven't checked any controllers yet in this project but based on my current and previous review I guess if I don't see much queries in your model (especially with the user model) then most of it will go to the controllers and/or views (which is bad).

2019-05-29 08:25 UTC, rvvergara commented on app/models/user.rb
> +  has_many :sent_requests,
While you've addressed my previous question regarding having a method that will list all `user`'s friends, I still highly encourage you to have such a method instead of having to write out a long query everytime you need a user's list of friends. This will make your controllers and views later on easier to build. 

Also this makes your data easier to reason about.

I am applying here the principle of **fat-model thin-controllers/views**. I am sure that later in your views you would want to list a user's friends, mutual friends with another user, etc. This will necessitate you to query over and over again the database (using the `where` statement you previously mentioned) just to do this. That will make your logic transfer more and more to your controllers, which isn't a good practice.

2019-05-29 08:25 UTC, rvvergara commented on app/models/friendship.rb
> +class Friendship < ApplicationRecord
Please see #5

2019-05-29 08:25 UTC, rvvergara commented on test/models/user_test.rb
> +class UserTest < ActiveSupport::TestCase
I highly highly encourage you guys to use RSPec for testing. For one it will make your specs easier to debug and easier to maintain. Secondly, RSpec's syntax is much readable. Third, fixtures, which Minitest uses, is brittle (easily breaks) than RSpec's factories. A professional benefit is that you'll find more companies using RSpec more than Minitest. Also RSpec has closer resemblance with Jest (which you will use when you get to the JavaScript sections). I hope these benefits convince you why it's great to convert into RSpec. :)

2019-06-05 04:00 UTC, rvvergara requested changes
Hi @efrapp and @userman95,

Pls see my latest review :) Please also check #6. Ok while I reviewed your `users_controller.rb` file, I assume that this review is still a continuation of our reviews solely for models. I hope the references and code snippets I provided will be helpful.

2019-06-05 07:49 UTC, userman95 commented on app/models/user.rb
> +  has_many :friend_requests, dependent: :destroy
ok . So if mike want to send to ryto a friend request it goes like this: ryto.friend_requests.create(friend: mike) .And ryto can see his friend requests like this: ryto.friend_requests.

2019-06-11 03:56 UTC, rvvergara requested changes
Hi @efrapp and @userman95,

Great job after our conversation! :) Pls see my updated review here. Your models are almost good to go and I suggest for the next review you already include some work on the controllers already. Most of my comments here are just for refinement of the friendship/friend_request records and for the specs.

2019-06-11 03:56 UTC, rvvergara commented on app/models/user.rb
> +  has_many :active_friendships,class_name: "Friendship",
Great job at this guys! :)

2019-06-11 03:56 UTC, rvvergara commented on app/models/friendship.rb
> +    def friendship_uniqueness
Guys I don't want to bog you down on this. But if you're interested, you can go further and enforce this uniqueness at the database level on top of this validation you are already doing. If you like to do this just reach out to me on slack :)

2019-06-11 03:56 UTC, rvvergara commented on app/models/friend_request.rb
> +  def accept
Probably we don't need this method anymore. We can simply use the CRUD actions for Friendship to create the associated friendship record :)

2019-06-11 03:56 UTC, rvvergara commented on app/models/friend_request.rb
> +  def decline
Likewise, perhaps we don't need this special method anymore. We can simply use the `destroy` directly when a user clicks on the `Decline Request` button

2019-06-11 03:56 UTC, rvvergara commented on spec/models/user_spec.rb
> +  context 'validation tests' do
Guys, i suggest the following organization for your specs to make it more readable:

```ruby
describe "validations" do
  context "complete user details" do
    it "is valid" do
      # expectations here
    end
  end
  
   context "name absent" do
      it "is invalid" do
        # expectations here
      end
   end
end
```

2019-06-11 15:58 UTC, efrapp commented on app/models/friend_request.rb
> +  def accept
Method removed. Also, the specs for models were updated to remove the `accept` method.

2019-06-11 16:03 UTC, efrapp commented on app/models/friend_request.rb
> +  def decline
Method removed. Also, the specs for models were updated.

2019-06-12 10:10 UTC, efrapp commented on spec/models/user_spec.rb
> +  context 'validation tests' do
We changed the `context` block with `describe` but we just used `context` in some sections because it wasn't needed to use it in all the specs.

2019-06-13 16:19 UTC, efrapp commented on app/models/friendship.rb
> +    def friendship_uniqueness
Ryan, I added the code to enforce uniqueness in the database side as you suggested but I had to use `before_validation` callback to give priority to the `check_duplicates` method, any other callback will run after validations so we can't get the desired result. Let me know your thoughts, please.

2019-06-13 16:25 UTC, efrapp commented
New code review sent for models

2019-06-24 02:14 UTC, rvvergara requested changes
Hi @efrapp and @userman95,

Ok now we're on controllers and views. Congratulations for making it this far into the project and into the program!! :) You guys are awesome!

## User Interface

I like the part that I can search for users :) Great job on this!

I can make a post (both text and image), comment on it (and delete my comment), like and unlike it. => Awesome!! How about making posts deletable?

I can send a friend request and also accept it (and delete a friend). It would be nice if I could see a notification that I have a friend request.

### User show page

Haha im wondering what this image is and what it is for?

![image](https://user-images.githubusercontent.com/6015315/59985926-d5d75380-9666-11e9-9202-3337e4bd0825.png)

### Editing my profile

We have an `update` action on our `users_controller` but how do I go to the Edit user page?

## Let's write specs for features

Please also see my annotations to some controller files.

2019-06-24 02:14 UTC, rvvergara commented on app/controllers/friendships_controller.rb
> +    @friendship = current_user.active_friendships.build(friend: @friend)
There isn't any major issue with this line, but I would like to suggest to make the attributes of `Friendship` consistent with `FriendRequest`. What I mean is that for example in this line of code, we are making the user that received the `FriendRequest` as the `active` friend. I suggest let's make the receiver of the `FriendRequest` the `friend_id` and the sender of the `FriendRequest` as the `user_id` in the `Friendship` record. If that's confusing, in code:

```ruby
@friendship = current_user.passive_friendships.build(user: @friend)
```
I think reflects more appropriately what is happening. Though again, if you sill prefer what you put here, it's all good :)

2019-06-24 02:14 UTC, rvvergara commented on app/controllers/posts_controller.rb
> +    if @post.save
This is a great idea of redirecting a user back to the page where he/she created the post. However, normally we'd like the `if else` block to be all about either successfully creating a post or not. To redirect a user back to the place where he/she has created a post I suggest you investigate using `redirect_to_session`. I think this was used in the Rails Tutorial Book

2019-06-25 00:52 UTC, rvvergara requested changes
@efrapp and @userman95,

We're getting closer and closer to finishing this project. You guys are rocking it! :) 

Ok for your controllers, all is good now. 

For your views. I didn't dig too deep into each file as I trust that you are going to DRY them up with the appropriate use of partials. Just also watch out that you're not placing too much logic into your views (your views should be totally dumb and will just get their logic from the helpers/controllers). 

Some remaining tasks that need to be done:

Please see #7 

Also let's pls write `feature` specs.

2019-06-30 23:56 UTC, rvvergara commented
Hi @efrapp  and @userman95,

All is well with your app:

### Project Specification

1. Core features are included in the plan:
    - [x] users accounts
    - [x] friendships
    - [x] posts & comments

### Crucial things to make project work

- [x] The project has a descriptive README.md
- [x] Project should be done collaboratively and that the commit history reflects that

#### Database 
- [x] Use Postgresql for your database from the beginning (not sqlite3)

#### Models

##### User
- [x] Can send Friend Requests to other Users
- [x] Can accept the Friend Request
- [x] Must accept the Friend Request to become friends
- [x] Can create a Post
- [x] Can Like Posts
- [x] Can comment on Posts

##### Post
- [x] Has many comments
- [x] Has many likes

#### Controllers and Actions

##### Sessions
- [x] You must be logged in to watch anything but the login page
- [x] Login should use the devise gem
- [x] Allows logging in using a Facebook account through Omniauth

##### Navigation bar
- [x] Shows the number of received Friend Requests

##### User
- [x] Can create a Profile with a Photo

###### `:index`
- [x] Lists all users
- [x] Displays a button next to users to send a friend request
- [x] Displays if a friend request was sent
- [x] Displays if a user is already a friend
- [x] The current user can send Friend Requests to other Users

###### `:show`

- [x] Displays profile information
- [x] Displays the avatar
- [x] Displays the user's posts

##### Post

###### `:new`
- [x] The current user can create a new post

###### `:index`
- [x] Show recent posts from friends

###### `:show`
- [x] Displays the content
- [x] Displays the author
- [x] Displays the comments
- [x] Displays the likes
- [x] The current user can like the post
- [x] The current user comment on the post

In addition, you have written thorough tests for your models and features. That's already enough for me to give you a:

# :+1: 

Great work you guys and you've shown much dedication in learning and excellence. :) Off to your next adventure!

2019-07-01 00:00 UTC, userman95 commented
thanks Ryan ! You were great aswell! :D See you in next projects

2019-07-01 00:00 UTC, merged

2019-07-02 10:47 UTC, efrapp commented
Thank you @rvvergara. I learned cool things from your code reviews.